title: "Your Name - Freelance Scientist"
author: "Your Name"
email: "your.email@example.com"
description: "Open-source solutions for marine science and ecosystem monitoring."
baseurl: ""
url: "https://yourusername.github.io"
github_username: "yourusername"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
collections:
  pages:
    output: true
    permalink: /:path/
