title: "WildFlux"
author: "WildFlux"
email: "mohanjulien@examplegmail.com"
description: "Open-source solution for science and creativity."
baseurl: ""
url: "https://kernythree.github.io"
github_username: "kernythree"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
collections:
  pages:
    output: true
    permalink: /:path/
